// webclient-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Twitter Sentiment Analysis';
}

<app-navbar></app-navbar>
<div class="container">
    <app-overlay></app-overlay>
    <app-messages></app-messages>
    <router-outlet></router-outlet>    
</div>

// webclient-react/src/App.js
import React, { Component } from 'react';
import './App.css';
import Navigation from './components/navbar/Navigation';
import TwitterSentimentAnalysis from './components/twitter-sentiment-analysis/TwitterSentimentAnalysis';

class App extends Component {
  render() {
    return (
      <div className="App" class="container">
        <Navigation/>
        <TwitterSentimentAnalysis/>
      </div>
    );
  }
}

export default App;
