// webclient-react/src/components/twitter-sentiment-analysis/TwitterSentimentAnalysis.js
import React from 'react';



class TwitterSentimentAnalysis extends React.Component {
    render() {
        return (
            <div class="panel panel-primary" >

                <div class="panel-body">

                    <form id="searchForm">
                        <fieldset>
                            <legend>Search</legend>
                            <div class="form-group">
                                <label for="queryTerms" class="form-control-label">Query Terms</label>
                                <input type="text"

                                    name="queryTerms"
                                    class="form-control form-control-lg"
                                    autofocus="autofocus"
                                    tabindex="1" />
                            </div>
                            <div class="form-group">
                                <label for="tweetCount" class="form-control-label"># of Tweets</label>
                                <output name="tweetCountOutput" id="tweetCountOutput"></output>
                                <input type="range"
                                    class="form-control"
                                    id="tweetCount"
                                    name="tweetCount"
                                    min="10" max="500" step="10" oninput="tweetCountOutput.value = tweetCount.value"
                                    tabindex="2" />
                            </div>

                            <input type="submit" class="btn btn-primary" tabindex="3" />
                        </fieldset>
                    </form>
                    <div id="resultsChart"></div>

                    <hr />
                    <div id="resultsTable"></div>
                </div>

            </div>
        )
    }
}

export default TwitterSentimentAnalysis;

// webclient-angular/src/app/twitter-sentiment-analysis/twitter-sentiment-analysis.component.ts
import { Component, OnInit, ViewEncapsulation, Input } from '@angular/core';
import { TwitterSentimentAnalysisService } from './twitter-sentiment-analysis.service'
import { TwitterSentimentAnalyzer } from './twitter-sentiment-analyzer';


@Component({
  selector: 'app-twitter-sentiment-analysis',
  templateUrl: './twitter-sentiment-analysis.component.html',
  styleUrls: ['./twitter-sentiment-analysis.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class TwitterSentimentAnalysisComponent implements OnInit {

  @Input() model: TwitterSentimentAnalyzer;
  resultsTotal: string;
  isLoading: boolean;
  dsvData: string;
  delimiter: string;
  donutChartObj: object;
  
  constructor(private twitterSentimentAnalyisService: TwitterSentimentAnalysisService) { }

  ngOnInit() {
    this.model = new TwitterSentimentAnalyzer("", 100);
    this.dsvData = "";
    this.delimiter = "~";
    this.donutChartObj = {};
  }

  getSAResults(): void {
    this.isLoading = true;
    this.twitterSentimentAnalyisService
      .getSAResults(this.model.queryTerms, this.model.tweetCount)
      .subscribe(
        response => {
          this.donutChartObj = response[0];
          this.dsvData = response[1]; 
        }, 
        err => {
          this.isLoading = false;
          console.error('err:', err.message);
        }, 
        () => {
          this.isLoading = false;
        }
      );
  }

}


<div class="panel panel-primary" >

  <div class="panel-body">

      <form (ngSubmit)="getSAResults()" id="searchForm">
          <fieldset>
              <legend>Search</legend>
              <div class="form-group">
                  <label for="queryTerms" class="form-control-label">Query Terms</label>
                  <input type="text" 
                  [(ngModel)]="model.queryTerms"
                  name="queryTerms" 
                  class="form-control form-control-lg" 
                  autofocus="autofocus"
                  tabindex="1"/>
              </div>
              <div class="form-group">
                  <label for="tweetCount" class="form-control-label"># of Tweets</label>
                  <output name="tweetCountOutput" id="tweetCountOutput">{{model.tweetCount}}</output>
                  <input type="range" 
                  class="form-control" 
                  id="tweetCount" 
                  [(ngModel)]="model.tweetCount"
                  name="tweetCount"
                      min="10" max="500" step="10" oninput="tweetCountOutput.value = tweetCount.value" 
                      tabindex="2"/>
              </div>

              <input type="submit" class="btn btn-primary" tabindex="3"/>
          </fieldset>
      </form>
      <loader [isActive]="isLoading"></loader>
      <donut-chart [donutData]="donutChartObj"></donut-chart>
      <hr />
      <dsv-table [delimiter]="delimiter" [dsvdata]="dsvData"></dsv-table>
      <hr />
  </div>

</div>
